version: '3.7'
services:
  floolon-admin-api:
    container_name: floolon-admin-api
    restart: always
    build:
      # 指定Docker构建上下文的路径，通常是Dockerfile所在的目录
      context: ./
      # 指定Dockerfile的路径，相对于构建上下文
      dockerfile: ./Dockerfile
    # 定义该服务所依赖的其他服务，它们将按照依赖顺序启动
    depends_on:
      # 依赖名为'mysql-container'的服务
      - mysql-container
      # 依赖名为'redis-container'的服务
      - redis-container
    # 端口映射，将宿主机的3000端口映射到容器的3000端口
    ports:
      - '8081:8081'
      - '8080:8080'
    environment:
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    # 定义一个名为'mysql-container'的服务，使用mysql镜像

  mysql-container:
    container_name: mysql-container
    # 指定使用mysql官方Docker镜像
    image: mysql
    # 端口映射，将宿主机的3306端口映射到容器的3306端口
    ports:
      - '3306:3306'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci #设置utf8字符集
    # 数据卷配置，用于持久化存储
    volumes:
      - D:\foolon-admin-mysql:/var/lib/mysql
      - ./sql/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: foolon-admin
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Shanghai

  # 定义一个名为'redis-container'的服务，使用redis镜像
  redis-container:
    container_name: redis-container
    # 指定使用redis官方Docker镜像
    image: redis
    # 端口映射，将宿主机的6379端口映射到容器的6379端口
    ports:
      - '6379:6379'
    command: redis-server --requirepass floolon-admin:H9tCSNrpQXSpLYNmJ=EJ
    # 数据卷配置，用于持久化存储
    volumes:
      # 将宿主机的/Users/yunmu/Desktop/redis目录映射到容器的/data目录
      - D:\foolon-admin-redis:/data
    environment:
      - TZ=Asia/Shanghai
