/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const ElNotification: typeof import('element-plus/es')['ElNotification']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElSelectOptions: typeof import('element-plus/es')['ElSelectOptions']
}
